name: Publish website

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"  # optional daily rebuild


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        run: |
          cd site
          quarto render
          touch _site/.nojekyll    # prevent Jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/_site
